let productDetails = [
        // Case

        // {
        //     name: '',
        //     brand: '',
        //     productDimensions: '',
        //     itemModelNumber: '',
        //     manufacturer: '',
        //     series: '',
        //     color: '',
        //     formFactor: '',
        //     maximumFrontFans: '',
        //     maximumRearFans: '',
        //     maximumTopFans: '',
        //     frontFanDiameters: '',
        //     rearFansInstalled: '',
        //     LiquidCoolingAllowed: '',
        //     motherboardCompatability: '',
        //     supportedHDDsizes: '',
        //     numberOfHDDs: '',
        //     Material: '',
        //     itemWeight: '',
        //     numberOfUSBports: '',
        // },

        {
            name: 'Arcadia II',
            brand: 'RAIJINTEK Corporation',
            productDimensions: '18.5 x 37.5 x 46 cm; 3.9 Kilograms',
            itemModelNumber: '0R20B00093',
            manufacturer: 'RAIJINTEK',
            series: 'Arcadia II',
            color: 'Black',
            sidePanel: 'Perforated Steel',
            maximumFrontFans: '2',
            maximumRearFans: '4',
            maximumTopFans: '1',
            frontFanDiameters: '120mm, 140mm',
            rearFansInstalled: '1 x 120mm',
            LiquidCoolingAllowed: 'Yes',
            motherboardCompatability: 'ATX',
            supportedHDDsizes: '2.5, 3.5, 5.25',
            numberOfHDDs: '4',
            Material: 'Aluminium',
            itemWeight: '3.9kg',
            numberOfUSBports: '2',
        },
        {
            name: 'Focus G',
            brand: 'Fractal Design Store',
            productDimensions: '45 x 43 x 19 cm; 4.5 Kilograms',
            itemModelNumber: 'FD-CA-FOCUS-BK-W',
            manufacturer: 'Fractal Design Store',
            series: 'Focus G',
            color: 'Black',
            sidePanel: 'Fabric',
            maximumFrontFans: '2',
            maximumRearFans: '2',
            maximumTopFans: '2',
            frontFanDiameters: '120mm',
            rearFansInstalled: '2 x 120mm',
            LiquidCoolingAllowed: 'Yes',
            motherboardCompatability: 'ATX',
            supportedHDDsizes: '2.5, 3.5, 5.25',
            numberOfHDDs: '6',
            Material: 'Plastic',
            itemWeight: '5.9kg',
            numberOfUSBports: '2',
        },
        {
            name: 'NR600',
            brand: 'Cooler Master',
            productDimensions: '29 x 54 x 54 cm; 8 Grams',
            itemModelNumber: 'MCB-NR600-KGNN-S00',
            manufacturer: 'Coolermaster',
            series: 'Cooler Master',
            color: 'Black',
            sidePanel: 'Tempered Glass',
            maximumFrontFans: '2',
            maximumRearFans: '2',
            maximumTopFans: '1',
            frontFanDiameters: '120mm',
            rearFansInstalled: '1 x 120mm',
            LiquidCoolingAllowed: 'Yes',
            motherboardCompatability: 'ATX',
            supportedHDDsizes: '2.5, 3.5',
            numberOfHDDs: '4',
            Material: 'Steel',
            itemWeight: '4.9kg',
            numberOfUSBports: '2',
        },
        {
            name: 'Enthoo Elite',
            brand: 'Phanteks',
            productDimensions: '57.4 x 24 x 59.94 cm; 17 Kilograms',
            itemModelNumber: 'PH-ES719LTG_DBK01',
            manufacturer: 'PHANTEKS',
            series: 'Phanteks Enthoo',
            color: 'Grey',
            sidePanel: 'Tempered Glass',
            maximumFrontFans: '2',
            maximumRearFans: '2',
            maximumTopFans: '1',
            frontFanDiameters: '120mm, 140mm',
            rearFansInstalled: '2 x 120mm',
            LiquidCoolingAllowed: 'No',
            motherboardCompatability: 'ATX',
            supportedHDDsizes: '2.5, 3.5, 5.2',
            numberOfHDDs: '6',
            Material: 'Aluminium',
            itemWeight: '17kg',
            numberOfUSBports: '2',
        },
        {
            name: 'Enthoo Primo',
            brand: 'Phanteks',
            productDimensions: '59.99 x 24.99 x 65 cm; 17.9 Kilograms',
            itemModelNumber: 'PH-ES813P_BL',
            manufacturer: 'Phanteks',
            series: 'Phanteks Enthoo',
            color: 'Black',
            sidePanel: 'Tempered Glass',
            maximumFrontFans: '2',
            maximumRearFans: '2',
            maximumTopFans: '1',
            frontFanDiameters: '120mm',
            rearFansInstalled: '1',
            LiquidCoolingAllowed: 'Yes',
            motherboardCompatability: 'ATX',
            supportedHDDsizes: '2.5, 3.5',
            numberOfHDDs: '4',
            Material: 'Steel',
            itemWeight: '17.9kg',
            numberOfUSBports: '2',
        },
        {
            name: 'Cosmos C700P',
            brand: 'Cooler Master',
            productDimensions: '30.6 x 63.9 x 65.1 cm; 21.6 Kilograms',
            itemModelNumber: 'MCC-C700P-KG5N-S00',
            manufacturer: 'Coolermaster',
            series: 'MCS-S600-KN5N-S00',
            color: 'Black',
            sidePanel: 'Perforated Steel',
            maximumFrontFans: '2',
            maximumRearFans: '2',
            maximumTopFans: '1',
            frontFanDiameters: '120mm, 140mm',
            rearFansInstalled: '2 x 120mm',
            LiquidCoolingAllowed: 'No',
            motherboardCompatability: 'Extended ATX',
            supportedHDDsizes: '2.5, 3.5',
            numberOfHDDs: '4',
            Material: 'Plastic',
            itemWeight: '21.6kg',
            numberOfUSBports: '4',
        },
        {
            name: 'Dark Base Pro 900',
            brand: 'Be Quiet',
            productDimensions: '57.7 x 24.3 x 58.6 cm; 1 Kilograms',
            itemModelNumber: 'BGW16',
            manufacturer: 'BE QUIET',
            series: 'Dark Base Pro 900 rev. 2',
            color: 'Silver rev. 2',
            sidePanel: 'Aluminium',
            maximumFrontFans: '2',
            maximumRearFans: '1',
            maximumTopFans: '1',
            frontFanDiameters: '120mm',
            rearFansInstalled: '1 x 120mm',
            LiquidCoolingAllowed: 'Yes',
            motherboardCompatability: 'ATX',
            supportedHDDsizes: '2.5, 3.5',
            numberOfHDDs: '4',
            Material: 'Aluminium',
            itemWeight: '9kg',
            numberOfUSBports: '2',
        },
        {
            name: 'Define R6',
            brand: 'Fractal Design',
            productDimensions: '23 x 46 x 54 cm; 13 Kilograms',
            itemModelNumber: 'FD-CA-DEF-R6-BK',
            manufacturer: 'FRACTAL DESIGN',
            series: 'Define R Series',
            color: 'Black',
            sidePanel: 'Fabric',
            maximumFrontFans: '2',
            maximumRearFans: '1',
            maximumTopFans: '1',
            frontFanDiameters: '120mm',
            rearFansInstalled: '1 x 120mm',
            LiquidCoolingAllowed: 'No',
            motherboardCompatability: 'ATX',
            supportedHDDsizes: '2.5, 3.5',
            numberOfHDDs: '6',
            Material: 'Aluminum',
            itemWeight: '13kg',
            numberOfUSBports: '2',
        },
        {
            name: 'Lancool II',
            brand: 'Lian-Li',
            productDimensions: '55.88 x 29.21 x 55.88 cm; 13.38 Kilograms',
            itemModelNumber: 'LAN2MPX',
            manufacturer: 'Lian-li',
            series: 'Lian-Li Lancool',
            color: 'Performance',
            sidePanel: 'Tempered Steel',
            maximumFrontFans: '2',
            maximumRearFans: '2',
            maximumTopFans: '1',
            frontFanDiameters: '120mm',
            rearFansInstalled: '2 x 120mm',
            LiquidCoolingAllowed: 'No',
            motherboardCompatability: 'Mini ATX',
            supportedHDDsizes: '2.5, 3.5, 5.2',
            numberOfHDDs: '4',
            Material: 'Steel',
            itemWeight: '13.4kg',
            numberOfUSBports: '2',
        },
        {
            name: 'H500',
            brand: 'Cooler Master',
            productDimensions: '52.5 x 22.8 x 50.2 cm; 9.22 Kilograms',
            itemModelNumber: 'MCM-H500-IGNN-S01',
            manufacturer: 'Coolermaster',
            series: 'Cooler Master MasterCase',
            color: 'ARGB',
            sidePanel: 'Tempered Glass',
            maximumFrontFans: '2',
            maximumRearFans: '2',
            maximumTopFans: '1',
            frontFanDiameters: '200mm',
            rearFansInstalled: '1 x 120mm',
            LiquidCoolingAllowed: 'Yes',
            motherboardCompatability: 'Extended ATX',
            supportedHDDsizes: '2.5, 3.5',
            numberOfHDDs: '4',
            Material: 'Iron',
            itemWeight: '9.22kg',
            numberOfUSBports: '2',
        },
        {
            name: 'H710i',
            brand: 'NZXT',
            productDimensions: '49.4 x 23 x 51.6 cm; 12.3 Kilograms',
            itemModelNumber: 'CA-H710i-W1',
            manufacturer: 'NZXT',
            series: 'I-series',
            color: 'White/Black',
            sidePanel: 'Tempered Glass',
            maximumFrontFans: '2',
            maximumRearFans: '2',
            maximumTopFans: '1',
            frontFanDiameters: '140mm',
            rearFansInstalled: '1 x 120mm',
            LiquidCoolingAllowed: 'No',
            motherboardCompatability: 'Mini-ITX, Micro-ATX, EATX and ATX',
            supportedHDDsizes: '2.5, 3.5',
            numberOfHDDs: '4',
            Material: 'Aluminium',
            itemWeight: '12.3kg',
            numberOfUSBports: '2',
        },
        {
            name: 'Pure Base 500',
            brand: 'Be Quiet',
            productDimensions: '50.8 x 29.2 x 50.2 centimetres',
            itemModelNumber: 'BGW37',
            manufacturer: 'BE QUIET',
            series: 'Pure Base BE QUIET',
            color: 'Black',
            sidePanel: 'Tempered Glass',
            maximumFrontFans: '4',
            maximumRearFans: '2',
            maximumTopFans: '1',
            frontFanDiameters: '120mm, 140mm',
            rearFansInstalled: '2 x 140mm',
            LiquidCoolingAllowed: 'Yes',
            motherboardCompatability: 'ATX',
            supportedHDDsizes: '2.5, 3.5, 5.2',
            numberOfHDDs: '6',
            Material: 'Aluminium',
            itemWeight: '8kg',
            numberOfUSBports: '2',
        },
        {
            name: 'H510',
            brand: 'Be Quiet',
            productDimensions: '50.8 x 29.2 x 50.2 centimetres',
            itemModelNumber: 'BGW37',
            manufacturer: 'BE QUIET',
            series: 'BE QUIET H Series',
            color: 'Black',
            sidePanel: 'Tempered Glass',
            maximumFrontFans: '4',
            maximumRearFans: '2',
            maximumTopFans: '1',
            frontFanDiameters: '120mm, 140mm',
            rearFansInstalled: '1 x 120mm',
            LiquidCoolingAllowed: 'No',
            motherboardCompatability: 'ATX, M-ATX, Mini-ITX',
            supportedHDDsizes: '2.5, 3.5',
            numberOfHDDs: '4',
            Material: 'Steel',
            itemWeight: '8kg',
            numberOfUSBports: '2',
        },
        {
            name: 'P300',
            brand: 'Phanteks',
            productDimensions: '39.88 x 19.81 x 44.96 cm; 5.99 Kilograms',
            itemModelNumber: 'PH-EC300PTG_BW',
            manufacturer: 'PHANTEKS',
            series: 'Phanteks Enthoo',
            color: 'Black/White',
            sidePanel: 'Tempered Glass',
            maximumFrontFans: '4',
            maximumRearFans: '2',
            maximumTopFans: '1',
            frontFanDiameters: '120mm',
            rearFansInstalled: '1 x 120mm',
            LiquidCoolingAllowed: 'Yes',
            motherboardCompatability: 'ATX',
            supportedHDDsizes: '2.5, 3.5, 5.2',
            numberOfHDDs: '6',
            Material: 'Steel',
            itemWeight: '5.99kg',
            numberOfUSBports: '2',
        },
        {
            name: 'Enthoo Pro',
            brand: 'Phanteks',
            productDimensions: '55.88 x 23.49 x 53.34 cm',
            itemModelNumber: 'PH-ES614P_BK',
            manufacturer: 'Phanteks',
            series: 'Enthoo Pro',
            color: 'Black',
            sidePanel: 'Tempered Glass',
            maximumFrontFans: '2',
            maximumRearFans: '2',
            maximumTopFans: '1',
            frontFanDiameters: '120mm, 140mm',
            rearFansInstalled: '1 x 120mm',
            LiquidCoolingAllowed: 'No',
            motherboardCompatability: 'Micro ATX',
            supportedHDDsizes: '2.5, 3.5',
            numberOfHDDs: '4',
            Material: 'Plastic, Steel',
            itemWeight: '11.88kg',
            numberOfUSBports: '2',
        },
        {
            name: '760T V2',
            brand: 'Corsair',
            productDimensions: '64.01 x 34.04 x 66.55 cm',
            itemModelNumber: 'CC-9011074-WW',
            manufacturer: 'Corsair',
            series: 'CC-9011074-WW',
            color: 'White',
            sidePanel: 'Tempered Glass',
            maximumFrontFans: '2',
            maximumRearFans: '2',
            maximumTopFans: '1',
            frontFanDiameters: '120mm, 140mm',
            rearFansInstalled: '1 x 120mm',
            LiquidCoolingAllowed: 'Yes',
            motherboardCompatability: 'ATX, EATX, Micro-ATX, Mini-ITX, XL-ATX',
            supportedHDDsizes: '2.5, 3.5',
            numberOfHDDs: '4',
            Material: 'Aluminium',
            itemWeight: '11.16kg',
            numberOfUSBports: '2',
        },
        {
            name: '750D Airflow',
            brand: 'Corsair',
            productDimensions: '54.61 x 23.62 x 55.88 cm',
            itemModelNumber: 'CC-9011078-WW',
            manufacturer: 'Corsair',
            series: 'Corsair',
            color: 'Black',
            sidePanel: 'Tempered Glass',
            maximumFrontFans: '4',
            maximumRearFans: '2',
            maximumTopFans: '1',
            frontFanDiameters: '120mm',
            rearFansInstalled: '1 x 120mm',
            LiquidCoolingAllowed: 'Yes',
            motherboardCompatability: 'ATX, EATX, Micro-ATX, Mini-ITX, XL-ATX',
            supportedHDDsizes: '2.5, 3.5',
            numberOfHDDs: '6',
            Material: 'Aluminium, Steel',
            itemWeight: '9.71kg',
            numberOfUSBports: '2',
        },
        {
            name: 'Cosmos C700M',
            brand: 'Cooler Master',
            productDimensions: '65.02 x 30.48 x 65.02 cm',
            itemModelNumber: 'MCC-C700M-MG5N-S00',
            manufacturer: 'Coolermaster',
            series: 'Cooler Master',
            color: 'Black/Grey/White',
            sidePanel: 'Tempered Glass',
            maximumFrontFans: '4',
            maximumRearFans: '2',
            maximumTopFans: '1',
            frontFanDiameters: '120mm, 140mm',
            rearFansInstalled: '1 x 120mm',
            LiquidCoolingAllowed: 'No',
            motherboardCompatability: 'ATX, Micro ATX',
            supportedHDDsizes: '2.5, 3.5, 5.2',
            numberOfHDDs: '4',
            Material: 'Steel',
            itemWeight: '23.8kg',
            numberOfUSBports: '5',
        },
        {
            name: 'View 71 RGB',
            brand: 'Thermaltake',
            productDimensions: '59.2 x 27.4 x 57.7 centimetres',
            itemModelNumber: 'CA-1I7-00F1WN-01',
            manufacturer: 'Thermaltake',
            series: 'Thermaltake Take',
            color: 'RGB',
            sidePanel: 'Tempered Glass',
            maximumFrontFans: '2',
            maximumRearFans: '2',
            maximumTopFans: '1',
            frontFanDiameters: '120mm',
            rearFansInstalled: '1 x 120mm',
            LiquidCoolingAllowed: 'Yes',
            motherboardCompatability: 'Micro ATX',
            supportedHDDsizes: '2.5, 3.5',
            numberOfHDDs: '4',
            Material: 'Tempered Glass',
            itemWeight: '19.1kg',
            numberOfUSBports: '4',
        },   

        // CPU

        // {
        //     name: '',
        //     brand: '',
        //     productDimensions: '',
        //     itemModelNumber: '',
        //     manufacturer: '',
        //     series: '',
        //     CPUmodel: '',
        //     CPUspeed: '',
        //     processorCount: '',
        //     processorSocket: '',
        //     primaryCacheSize: '',
        //     secondaryCacheSize: '',
        //     wattage: '',
        //     cores: '',
        //     threads: '',
        //     GHZboost: '',
        //     unlocked: '',
        //     containsThermalPaste: '',
        //     onboardGraphics: '',
        //     PCIeVersion: '',
        // },

        {
            name: 'R3 3300X',
            brand: 'AMD',
            productDimensions: '4 x 4 x 0.6 cm; 510 Grams',
            itemModelNumber: 'Ryzen 3 3300X',
            manufacturer: 'AMD',
            series: 'AMD Ryzen',
            CPUmodel: 'Ryzen 3 3300X',
            CPUspeed: '3.9 GHz',
            processorCount: '4',
            processorSocket: 'Socket AM4',
            primaryCacheSize: '18 MB',
            secondaryCacheSize: '5 MB',
            wattage: '65',
            cores: '4',
            threads: '8',
            GHZboost: '3.9',
            unlocked: 'Yes',
            containsThermalPaste: 'Yes',
            onboardGraphics: 'Yes',
            PCIeVersion: '4.0',
        },
        {
            name: 'R5 3400G',
            brand: 'AMD',
            productDimensions: '4 x 4 x 0.6 cm; 510 Grams',
            itemModelNumber: 'Ryzen 5 3400G',
            manufacturer: 'AMD',
            series: 'AMD Ryzen',
            CPUmodel: 'Ryzen 5 3400G',
            CPUspeed: '3.7 GHz',
            processorCount: '4',
            processorSocket: 'Socket AM4',
            primaryCacheSize: '4 MB',
            secondaryCacheSize: '2 MB',
            wattage: '65',
            cores: '4',
            threads: '8',
            GHZboost: '4.2',
            unlocked: 'No',
            containsThermalPaste: 'Yes',
            onboardGraphics: 'No',
            PCIeVersion: '4.0',
        },
        {
            name: 'R5 3600X',
            brand: 'AMD',
            productDimensions: '4 x 4 x 0.6 cm; 510 Grams',
            itemModelNumber: 'Ryzen 5 3600X',
            manufacturer: 'FANTAT',
            series: 'AMD Ryzen',
            CPUmodel: 'Ryze 5 3600',
            CPUspeed: '3.8 GHz',
            processorCount: '6',
            processorSocket: 'Socket AM4',
            primaryCacheSize: '12 MB',
            secondaryCacheSize: '4 MB',
            wattage: '95',
            cores: '6',
            threads: '4',
            GHZboost: '4.0',
            unlocked: 'Yes',
            containsThermalPaste: 'Yes',
            onboardGraphics: 'Yes',
            PCIeVersion: '4.0',
        },
        {
            name: 'R7 5800X',
            brand: 'AMD',
            productDimensions: '4 x 4 x 0.6 cm; 79.38 Grams',
            itemModelNumber: 'AMD Ryzen 7 5800X',
            manufacturer: 'AMFP4',
            series: 'AMD Ryzen™ 7 5800X',
            CPUmodel: 'Ryzen 7',
            CPUspeed: '3.8 GHz',
            processorCount: '8',
            processorSocket: 'Socket AM4',
            primaryCacheSize: '36 MB',
            secondaryCacheSize: '4 MB',
            wattage: '105',
            cores: '8',
            threads: '6',
            GHZboost: '4.0',
            unlocked: 'Yes',
            containsThermalPaste: 'No',
            onboardGraphics: 'Yes',
            PCIeVersion: '4.0',
        },
        {
            name: 'R9 5950X',
            brand: 'AMD',
            productDimensions: '4.06 x 4.06 x 0.76 cm; 453.59 Grams',
            itemModelNumber: 'YD2600BBAFBOX',
            manufacturer: 'AMD',
            series: 'AMD Ryzen',
            CPUmodel: '80386',
            CPUspeed: '3.4 GHz',
            processorCount: '6',
            processorSocket: 'Socket AM4',
            primaryCacheSize: '6MB',
            secondaryCacheSize: '2MB',
            wattage: '90',
            cores: '12',
            threads: '6',
            GHZboost: '4.0',
            unlocked: 'Yes',
            containsThermalPaste: 'Yes',
            onboardGraphics: 'Yes',
            PCIeVersion: '4.0',
        },
        {
            name: 'R9 5900X',
            brand: 'AMD',
            productDimensions: '4 x 4 x 0.6 cm; 79.38 Grams',
            itemModelNumber: 'AMD Ryzen 9 5900X',
            manufacturer: 'AMD',
            series: 'AMD Ryzen',
            CPUmodel: 'Ryzen 9',
            CPUspeed: '3.8 GHz',
            processorCount: '8',
            processorSocket: 'Socket AM4',
            primaryCacheSize: '36 MB',
            secondaryCacheSize: '5 MB',
            wattage: '105',
            cores: '12',
            threads: '24',
            GHZboost: '4.8',
            unlocked: 'Yes',
            containsThermalPaste: 'No',
            onboardGraphics: 'Yes',
            PCIeVersion: '4.0',
        },
        {
            name: 'R5 5600X',
            brand: 'AMD',
            productDimensions: '4 x 4 x 0.6 cm; 79.38 Grams',
            itemModelNumber: 'AMD Ryzen 5 5600X',
            manufacturer: 'AMD',
            series: 'AMD Ryzen',
            CPUmodel: 'Ryzen 5',
            CPUspeed: '3.7 GHz',
            processorCount: '6',
            processorSocket: 'Socket AM4',
            primaryCacheSize: '10 MB',
            secondaryCacheSize: '2 MB',
            wattage: '65',
            cores: '6',
            threads: '12',
            GHZboost: '4.0',
            unlocked: 'Yes',
            containsThermalPaste: 'Yes',
            onboardGraphics: 'Yes',
            PCIeVersion: '3.5',
        },
        {
            name: 'R5 3600',
            brand: 'AMD',
            productDimensions: '4 x 4 x 0.6 cm; 45.36 Grams',
            itemModelNumber: 'Ryzen 5 3600',
            manufacturer: 'AMD',
            series: 'AMD Ryzen',
            CPUmodel: 'Ryzen 5',
            CPUspeed: '3.6 GHz',
            processorCount: '6',
            processorSocket: 'Socket AM4',
            primaryCacheSize: '32 MB',
            secondaryCacheSize: '5 MB',
            wattage: '65',
            cores: '12',
            threads: '6',
            GHZboost: '3.8',
            unlocked: 'No',
            containsThermalPaste: 'No',
            onboardGraphics: 'Yes',
            PCIeVersion: '4.0',
        },
        {
            name: 'R3 3200G',
            brand: 'AMD',
            productDimensions: '4 x 4 x 0.6 cm; 50 Grams',
            itemModelNumber: 'Ryzen 3 3200G',
            manufacturer: 'AMD',
            series: 'AMD Ryzen',
            CPUmodel: 'Ryzen 3 3200G',
            CPUspeed: '3.6 GHz',
            processorCount: '4',
            processorSocket: 'Socket AM4',
            primaryCacheSize: '4 MB',
            secondaryCacheSize: '1 MB',
            wattage: '65',
            cores: '4',
            threads: '4',
            GHZboost: '3.9',
            unlocked: 'No',
            containsThermalPaste: 'Yes',
            onboardGraphics: 'Yes',
            PCIeVersion: '4.0',
        },
        {
            name: 'R3 3100',
            brand: 'AMD',
            productDimensions: '13.1 x 7.1 x 13.4 cm; 410 Grams',
            itemModelNumber: 'Ryzen 3 3100',
            manufacturer: 'AMD',
            series: 'AMD Ryzen',
            CPUmodel: 'Ryzen 3 3200X',
            CPUspeed: '3.9 GHz',
            processorCount: '4',
            processorSocket: 'Socket AM4',
            primaryCacheSize: '18 MB',
            secondaryCacheSize: '4 MB',
            wattage: '65',
            cores: '4',
            threads: '8',
            GHZboost: '3.9',
            unlocked: 'No',
            containsThermalPaste: 'No',
            onboardGraphics: 'Yes',
            PCIeVersion: '4.0',
        },
        {
            name: '3000G',
            brand: 'AMD',
            productDimensions: '8.5 x 11.4 x 6 cm; 201.28 Grams',
            itemModelNumber: 'Ryzen 3000G',
            manufacturer: 'AMD',
            series: 'AMD Athlon',
            CPUmodel: 'Athlon 64 3000+',
            CPUspeed: '3500 MHz',
            processorCount: '2',
            processorSocket: 'Socket AM4',
            primaryCacheSize: '5MB',
            secondaryCacheSize: '1 MB',
            wattage: '35',
            cores: '2',
            threads: '4',
            GHZboost: '3.6',
            unlocked: 'No',
            containsThermalPaste: 'Yes',
            onboardGraphics: 'Yes',
            PCIeVersion: '4.0',
        },
        {
            name: 'TR 3960X',
            brand: 'AMD',
            productDimensions: '7.8 x 5.6 x 0.75 cm; 172 Grams',
            itemModelNumber: 'RYZEN THREADRIPPER 3960X',
            manufacturer: 'AMD',
            series: 'AMD Ryzen',
            CPUmodel: 'Ryzen Threadripper 3960X',
            CPUspeed: '4500 MHz',
            processorCount: '24',
            processorSocket: 'STRX4',
            primaryCacheSize: '140 MB',
            secondaryCacheSize: '20 MB',
            wattage: '280',
            cores: '24',
            threads: '48',
            GHZboost: '4.5',
            unlocked: 'Yes',
            containsThermalPaste: 'No',
            onboardGraphics: 'Yes',
            PCIeVersion: '4.0',
        },
        {
            name: 'TR 3970X',
            brand: 'AMD',
            productDimensions: '7.8 x 5.6 x 0.75 cm; 172 Grams',
            itemModelNumber: 'RYZEN THREADRIPPER 3970X',
            manufacturer: 'AMD',
            series: 'AMD Ryzen',
            CPUmodel: 'Ryzen Threadripper 3970X',
            CPUspeed: '4700 MHz',
            processorCount: '28',
            processorSocket: 'STRX4',
            primaryCacheSize: '160 MB',
            secondaryCacheSize: '20 MB',
            wattage: '280',
            cores: '24',
            threads: '48',
            GHZboost: '4.5',
            unlocked: 'Yes',
            containsThermalPaste: 'No',
            onboardGraphics: 'Yes',
            PCIeVersion: '4.0',
        },

        // GPU

        // {
        //     name: '',
        //     brand: '',
        //     productDimensions: '',
        //     itemModelNumber: '',
        //     manufacturer: '',
        //     series: '',
        //     videoOutput: '',
        //     graphicsCoprocessor: '',
        //     graphicsChipset: '',
        //     graphicsRAMtype: '',
        //     graphicsRAMsize: '',
        //     graphicsCardDescription: '',
        //     graphicsCardInterface: '',
        //     memoryClockSpeed: '',
        //     coreClockSpeed: '',
        //     processorSocket: '',
        //     displayPort: '',
        //     HDMI: '',
        //     overclockable: '',
        //     itemWeight: ''
        // },

        {
            name: 'RX 5700',
            brand: 'MSI',
            productDimensions: '23.2 x 4.6 x 12.6 cm; 794 Grams',
            itemModelNumber: 'RADEON RX 5700 XT MECH OC',
            manufacturer: 'MSI COMPUTER',
            series: 'MSI RADEON RX 5700 XT MECH OC',
            videoOutput: 'DisplayPort',
            graphicsCoprocessor: 'AMD FirePro V7800',
            graphicsChipset: 'AMD',
            graphicsRAMtype: 'DDR5 SDRAM',
            graphicsRAMsize: '8 GB',
            graphicsCardDescription: '',
            graphicsCardInterface: 'PCI-Express x16',
            memoryClockSpeed: '14000 MHz',
            coreClockSpeed: '1925 MHz',
            amountOfFans: '2',
            displayPort: '3',
            HDMI: '1',
            overclockable: 'Yes',
            itemWeight: '794 g'
        },
        {
            name: 'RX 5500XT',
            brand: 'Sapphire',
            productDimensions: '30 x 20 x 10 cm; 100 Grams',
            itemModelNumber: '11295-01-20G',
            manufacturer: 'SAPPHIRE',
            series: '11295-01-20G',
            videoOutput: 'HDMI',
            graphicsCoprocessor: 'AMD Radeon RX 5700',
            graphicsChipset: 'AMD',
            graphicsRAMtype: 'GDDR6',
            graphicsRAMsize: '8 GB',
            graphicsCardDescription: 'Dédié',
            graphicsCardInterface: 'PCI-Express x8',
            memoryClockSpeed: '12000 MHz',
            coreClockSpeed: '1845 MHz',
            amountOfFans: '2',
            displayPort: '2',
            HDMI: '1',
            overclockable: 'Yes',
            itemWeight: '100g'
        },       
        {
            name: 'RX 6800',
            brand: 'Sapphire',
            productDimensions: '43.18 x 24.13 x 8.89 cm; 1.48 Kilograms',
            itemModelNumber: '11305-02-20G',
            manufacturer: 'SAPPHIRE',
            series: '11305-02-20G',
            videoOutput: 'DisplayPort, HDMI',
            graphicsCoprocessor: 'AMD Radeon RX 6800',
            graphicsChipset: 'AMD',
            graphicsRAMtype: 'GDDR6',
            graphicsRAMsize: '16 GB',
            graphicsCardDescription: 'AMD',
            graphicsCardInterface: 'PCI-Express x16',
            memoryClockSpeed: '16 GHz',
            coreClockSpeed: '2170 MHz',
            amountOfFans: '2',
            displayPort: '2',
            HDMI: '1',
            overclockable: 'Yes',
            itemWeight: '1.48kg'
        },
        {
            name: 'RTX 2060',
            brand: 'ASUS',
            productDimensions: '24.2 x 13 x 5.3 cm; 800 Grams',
            itemModelNumber: 'DUAL-RTX2060-O6G-EVO',
            manufacturer: 'Asus',
            series: 'DUAL-RTX2060-O6G-EVO',
            videoOutput: 'HDMI',
            graphicsCoprocessor: 'NVIDIA GeForce RTX 2060',
            graphicsChipset: 'NVIDIA',
            graphicsRAMtype: 'GDDR6',
            graphicsRAMsize: '6 GB',
            graphicsCardDescription: 'Dedicated',
            graphicsCardInterface: 'PCI-E',
            memoryClockSpeed: '14000 MHz',
            coreClockSpeed: '1200 MHz',
            amountOfFans: '2',
            displayPort: '2',
            HDMI: '1',
            overclockable: 'Yes',
            itemWeight: '800g'
        },
        {
            name: 'RX 570',
            brand: 'Sapphire',
            productDimensions: '23 x 12.5 x 4 cm; 1 Kilograms',
            itemModelNumber: 'M311326',
            manufacturer: 'SAPPHIRE',
            series: 'M311326',
            videoOutput: 'HDMI',
            graphicsCoprocessor: 'Radeon',
            graphicsChipset: 'AMD',
            graphicsRAMtype: 'GDDR5',
            graphicsRAMsize: '4 GB',
            graphicsCardDescription: 'AMD Radeon RX570',
            graphicsCardInterface: 'PCI-E',
            memoryClockSpeed: '1750 MHz',
            coreClockSpeed: '1284 MHz',
            amountOfFans: '2',
            displayPort: '2',
            HDMI: '1',
            overclockable: 'Yes',
            itemWeight: '1kg'
        },
        {
            name: 'RX 5600XT',
            brand: 'ASUS',
            productDimensions: '28.3 x 13.2 x 5.2 cm; 450 Grams',
            itemModelNumber: '90YV0EJ1-M0NA00',
            manufacturer: 'Asus',
            series: '90YV0EJ1-M0NA00',
            videoOutput: 'HDMI',
            graphicsCoprocessor: 'AMD Radeon RX 560',
            graphicsChipset: 'AMD',
            graphicsRAMtype: 'GDDR6',
            graphicsRAMsize: '6 GB',
            graphicsCardDescription: 'Dedicated',
            graphicsCardInterface: 'PCI-Express x8',
            memoryClockSpeed: '1770 MHz',
            coreClockSpeed: '1440 MHz',
            amountOfFans: '2',
            displayPort: '2',
            HDMI: '1',
            overclockable: 'Yes',
            itemWeight: '450g'
        },
        {
            name: 'GTX 1660S',
            brand: 'Gigabyte',
            productDimensions: '4 x 22.4 x 12.1 cm; 560 Grams',
            itemModelNumber: 'GV-N166SOC-6GD',
            manufacturer: 'Gigabyte',
            series: 'GV-N166SOC-6GD',
            videoOutput: 'HDMI',
            graphicsCoprocessor: 'NVIDIA GeForce GTX1660 SUPER',
            graphicsChipset: 'NVIDIA',
            graphicsRAMtype: 'GDDR6',
            graphicsRAMsize: '6 GB',
            graphicsCardDescription: 'GEF GTX1660',
            graphicsCardInterface: 'PCI-Express x16',
            memoryClockSpeed: '14000 MHz',
            coreClockSpeed: '1440 MHz',
            amountOfFans: '2',
            displayPort: '2',
            HDMI: '1',
            overclockable: 'Yes',
            itemWeight: '560g'
        },
        {
            name: 'RTX 3090',
            brand: 'MSI',
            productDimensions: '33.5 x 14.01 x 5.6 cm; 1.4 Kilograms',
            itemModelNumber: 'GeForce RTX™ 3090 GAMING X TRIO 24G',
            manufacturer: 'MSI COMPUTER',
            series: 'GeForce RTX™ 3090 GAMING X TRIO 24G',
            videoOutput: 'HDMI',
            graphicsCoprocessor: 'NVIDIA GeForce RTX 3090',
            graphicsChipset: 'NVIDIA',
            graphicsRAMtype: 'GDDR6',
            graphicsRAMsize: '24 GB',
            graphicsCardDescription: 'GEF RTX3090',
            graphicsCardInterface: 'PCI-Express x4',
            memoryClockSpeed: '1345 MHz',
            coreClockSpeed: '1220 MHz',
            amountOfFans: '3',
            displayPort: '2',
            HDMI: '1',
            overclockable: 'Yes',
            itemWeight: '1.4kg'
        },
        {
            name: 'RTX 3080',
            brand: 'MSI',
            productDimensions: '33.5 x 14.01 x 5.6 cm; 1.4 Kilograms',
            itemModelNumber: 'GeForce RTX™ 3080 GAMING X TRIO 24G',
            manufacturer: 'MSI COMPUTER',
            series: 'GeForce RTX™ 3080 GAMING X TRIO 24G',
            videoOutput: 'HDMI',
            graphicsCoprocessor: 'NVIDIA GeForce RTX 3080',
            graphicsChipset: 'NVIDIA',
            graphicsRAMtype: 'GDDR6',
            graphicsRAMsize: '24 GB',
            graphicsCardDescription: 'GEF RTX3090',
            graphicsCardInterface: 'PCI-Express x4',
            memoryClockSpeed: '1345 MHz',
            coreClockSpeed: '1220 MHz',
            amountOfFans: '3',
            displayPort: '2',
            HDMI: '1',
            overclockable: 'Yes',
            itemWeight: '1.4kg'
        },
        {
            name: 'RTX 3060',
            brand: 'MSI',
            productDimensions: '33.5 x 14.01 x 5.6 cm; 1.4 Kilograms',
            itemModelNumber: 'GeForce RTX™ 3060 GAMING X TRIO 24G',
            manufacturer: 'MSI COMPUTER',
            series: 'GeForce RTX™ 3080 GAMING X TRIO 24G',
            videoOutput: 'HDMI',
            graphicsCoprocessor: 'NVIDIA GeForce RTX 3060',
            graphicsChipset: 'NVIDIA',
            graphicsRAMtype: 'GDDR6',
            graphicsRAMsize: '24 GB',
            graphicsCardDescription: 'GEF RTX3090',
            graphicsCardInterface: 'PCI-Express x4',
            memoryClockSpeed: '1345 MHz',
            coreClockSpeed: '1220 MHz',
            amountOfFans: '3',
            displayPort: '2',
            HDMI: '1',
            overclockable: 'Yes',
            itemWeight: '1.4kg'
        },
        {
            name: 'GTX 1650',
            brand: 'ASUS',
            productDimensions: '20.6 x 12.5 x 4.6 cm; 900 Grams',
            itemModelNumber: '2057624',
            manufacturer: 'Asus',
            series: '2057624',
            videoOutput: 'HDMI',
            graphicsCoprocessor: 'NVIDIA GeForce GTX 1650',
            graphicsChipset: 'NVIDIA',
            graphicsRAMtype: 'GDDR6',
            graphicsRAMsize: '4 GB',
            graphicsCardDescription: '',
            graphicsCardInterface: 'PCI-E',
            memoryClockSpeed: '1620 MHz',
            coreClockSpeed: '1440 MHz',
            amountOfFans: '2',
            displayPort: '2',
            HDMI: '1',
            overclockable: 'Yes',
            itemWeight: '900g'
        },       
        {
            name: 'RTX 2060 OC',
            brand: 'MSI',
            productDimensions: '33.5 x 14.01 x 5.6 cm; 1.4 Kilograms',
            itemModelNumber: 'GeForce RTX™ 2060 GAMING X TRIO 24G',
            manufacturer: 'MSI COMPUTER',
            series: 'GeForce RTX™ 2060 GAMING X TRIO 24G',
            videoOutput: 'HDMI',
            graphicsCoprocessor: 'NVIDIA GeForce RTX 2060',
            graphicsChipset: 'NVIDIA',
            graphicsRAMtype: 'GDDR6',
            graphicsRAMsize: '24 GB',
            graphicsCardDescription: 'GEF RTX2090',
            graphicsCardInterface: 'PCI-Express x4',
            memoryClockSpeed: '1345 MHz',
            coreClockSpeed: '1220 MHz',
            amountOfFans: '3',
            displayPort: '2',
            HDMI: '1',
            overclockable: 'Yes',
            itemWeight: '1.4kg'
        },
        {
            name: 'RX 5700 XT',
            brand: 'MSI',
            productDimensions: '23.2 x 4.6 x 12.6 cm; 794 Grams',
            itemModelNumber: 'RADEON RX 5700 XT MECH OC',
            manufacturer: 'MSI COMPUTER',
            series: 'MSI RADEON RX 5700 XT MECH OC',
            videoOutput: 'HDMI',
            graphicsCoprocessor: 'AMD FirePro V7800',
            graphicsChipset: 'AMD',
            graphicsRAMtype: 'DDR5 SDRAM',
            graphicsRAMsize: '8 GB',
            graphicsCardDescription: 'RAD RX5700',
            graphicsCardInterface: 'PCI-Express x16',
            memoryClockSpeed: '14000 MHz',
            coreClockSpeed: '1440 MHz',
            amountOfFans: '2',
            displayPort: '2',
            HDMI: '1',
            overclockable: 'Yes',
            itemWeight: '794g'
        },
        {
            name: 'RX 6800',
            brand: 'MSI',
            productDimensions: '23.2 x 4.6 x 12.6 cm; 794 Grams',
            itemModelNumber: 'RADEON RX 6800 XT MECH OC',
            manufacturer: 'MSI COMPUTER',
            series: 'MSI RADEON RX 6800 XT MECH OC',
            videoOutput: 'HDMI',
            graphicsCoprocessor: 'AMD FirePro V7800',
            graphicsChipset: 'AMD',
            graphicsRAMtype: 'DDR5 SDRAM',
            graphicsRAMsize: '8 GB',
            graphicsCardDescription: 'RAD RX6800',
            graphicsCardInterface: 'PCI-Express x16',
            memoryClockSpeed: '14000 MHz',
            coreClockSpeed: '1440 MHz',
            amountOfFans: '2',
            displayPort: '2',
            HDMI: '1',
            overclockable: 'Yes',
            itemWeight: '794g'
        },
        {
            name: 'RX 6900',
            brand: 'MSI',
            productDimensions: '23.2 x 4.6 x 12.6 cm; 794 Grams',
            itemModelNumber: 'RADEON RX 6900 XT MECH OC',
            manufacturer: 'MSI COMPUTER',
            series: 'MSI RADEON RX 6900 XT MECH OC',
            videoOutput: 'HDMI',
            graphicsCoprocessor: 'AMD FirePro V7800',
            graphicsChipset: 'AMD',
            graphicsRAMtype: 'DDR5 SDRAM',
            graphicsRAMsize: '8 GB',
            graphicsCardDescription: 'RAD RX6900',
            graphicsCardInterface: 'PCI-Express x16',
            memoryClockSpeed: '14000 MHz',
            coreClockSpeed: '1440 MHz',
            amountOfFans: '2',
            displayPort: '2',
            HDMI: '1',
            overclockable: 'Yes',
            itemWeight: '794g'
        },
        {
            name: 'RX 560',
            brand: 'MSI',
            productDimensions: '24 x 12 x 4 cm; 320 Grams',
            itemModelNumber: 'RX 560 AERO ITX 4G OC',
            manufacturer: 'MSI COMPUTER',
            series: 'RX 560 AERO ITX 4G OC',
            videoOutput: 'HDMI',
            graphicsCoprocessor: 'NVIDIA GeForce RTX 2070',
            graphicsChipset: 'AMD',
            graphicsRAMtype: 'DDR5 SDRAM',
            graphicsRAMsize: '512 MB',
            graphicsCardDescription: 'AMD Radeon RX560',
            graphicsCardInterface: 'PCI-Express x16',
            memoryClockSpeed: '4000 MHz',
            coreClockSpeed: '1175 MHz',
            amountOfFans: '1',
            displayPort: '2',
            HDMI: '2',
            overclockable: 'Yes',
            itemWeight: '320g'
        },
        {
            name: 'RTX 2070',
            brand: 'MSI',
            productDimensions: '25.7 x 4.1 x 12.7 cm; 856 Grams',
            itemModelNumber: 'RTX 2070 SUPER VENTUS OC',
            manufacturer: 'MSI COMPUTER',
            series: 'MSI Nvidia RTX2070 Super Ventus OC 8GB Fan GDDR6 DP/HDMI PCI Express Graphics Card',
            videoOutput: 'HDMI',
            graphicsCoprocessor: 'NVIDIA GeForce RTX 2070',
            graphicsChipset: 'NVIDIA',
            graphicsRAMtype: 'GDDR6',
            graphicsRAMsize: '8 GB',
            graphicsCardDescription: 'Dedicated',
            graphicsCardInterface: 'PCI-Express x16',
            memoryClockSpeed: '1785 MHz',
            coreClockSpeed: '1220 MHz',
            amountOfFans: '2',
            displayPort: '2',
            HDMI: '2',
            overclockable: 'Yes',
            itemWeight: '856 g'
        },
        {
            name: 'RTX 2080',
            brand: 'MSI',
            productDimensions: '25.7 x 4.1 x 12.7 cm; 856 Grams',
            itemModelNumber: 'RTX 2080 SUPER VENTUS OC',
            manufacturer: 'MSI COMPUTER',
            series: 'MSI Nvidia RTX2080 Super Ventus OC 8GB Fan GDDR6 DP/HDMI PCI Express Graphics Card',
            videoOutput: 'HDMI',
            graphicsCoprocessor: 'NVIDIA GeForce RTX 2080',
            graphicsChipset: 'NVIDIA',
            graphicsRAMtype: 'GDDR6',
            graphicsRAMsize: '8 GB',
            graphicsCardDescription: 'Dedicated',
            graphicsCardInterface: 'PCI-Express x16',
            memoryClockSpeed: '1785 MHz',
            coreClockSpeed: '1220 MHz',
            amountOfFans: '2',
            displayPort: '2',
            HDMI: '2',
            overclockable: 'Yes',
            itemWeight: '856 g'
        },
        {
            name: 'RTX 3070',
            brand: 'MSI',
            productDimensions: '25.7 x 4.1 x 12.7 cm; 856 Grams',
            itemModelNumber: 'RTX 3070 SUPER VENTUS OC',
            manufacturer: 'MSI COMPUTER',
            series: 'MSI Nvidia RTX3070 Super Ventus OC 8GB Fan GDDR6 DP/HDMI PCI Express Graphics Card',
            videoOutput: 'HDMI',
            graphicsCoprocessor: 'NVIDIA GeForce RTX 3070',
            graphicsChipset: 'NVIDIA',
            graphicsRAMtype: 'GDDR6',
            graphicsRAMsize: '8 GB',
            graphicsCardDescription: 'Dedicated',
            graphicsCardInterface: 'PCI-Express x16',
            memoryClockSpeed: '1785 MHz',
            coreClockSpeed: '1220 MHz',
            amountOfFans: '2',
            displayPort: '2',
            HDMI: '2',
            overclockable: 'Yes',
            itemWeight: '856 g'
        },

        // HDDs

        // {
        //     name: '',
        //     brand: '',
        //     productDimensions: '',
        //     itemModelNumber: '',
        //     manufacturer: '',
        //     series: '',
        //     color: '',
        //     formFactor: '',
        //     hardDriveSize: '',
        //     hardDiskDescription: '',
        //     wattage: '',
        //     powerSource: '',
        //     revolutionsPerMinute: '',
        //     hardwareInterface: '',
        //     readSpeed: '',
        //     writeSpeed: '',
        //     cacheSize: '',
        //     warranty: '',
        //     compatibleDevices: '',
        //     SATAcableIncluded: ''
        // },

        {
            name: 'Barracuda 2TB HDD',
            brand: 'Seagate',
            productDimensions: '10.03 x 6.99 x 0.71 cm; 90.72 Grams',
            itemModelNumber: 'ST2000LMZ15',
            manufacturer: '	SEAGATE',
            series: 'ST2000LMZ15',
            color: 'Silver',
            formFactor: '2.5"',
            hardDriveSize: '2000 GB',
            hardDiskDescription: 'HDD',
            wattage: '8',
            powerSource: 'System powered',
            revolutionsPerMinute: '5400',
            hardwareInterface: 'SATA 6.0 Gb/s',
            readSpeed: '140 MBs',
            writeSpeed: '140',
            cacheSize: '128',
            warranty: '24 months',
            compatibleDevices: 'Desktop',
            SATAcableIncluded: 'Yes'
        },

        {
            name: 'Toshiba 4TB HDD',
            brand: 'Toshiba',
            productDimensions: '14.7 x 10.18 x 2.61 cm; 720 Grams',
            itemModelNumber: 'HDEXR01ZNA51',
            manufacturer: 'Toshiba',
            series: 'N300',
            color: 'Silver',
            formFactor: '3.5"',
            hardDriveSize: '4 TB',
            hardDiskDescription: 'HDD',
            wattage: '10',
            powerSource: 'AC 100-240v, 50/60hz',
            revolutionsPerMinute: '7200',
            hardwareInterface: 'SATA 6.0 Gb/s',
            readSpeed: '140 MBs',
            writeSpeed: '140',
            cacheSize: '128',
            warranty: '24 months',
            compatibleDevices: 'Desktop',
            SATAcableIncluded: 'Yes'
        },

        {
            name: 'Toshiba 6TB HDD',
            brand: 'Toshiba',
            productDimensions: '14.7 x 10.18 x 2.61 cm; 720 Grams',
            itemModelNumber: 'HDEXR01ZNA51',
            manufacturer: 'Toshiba',
            series: 'N300',
            color: 'Silver',
            formFactor: '3.5"',
            hardDriveSize: '6 TB',
            hardDiskDescription: 'HDD',
            wattage: '10',
            powerSource: 'AC 100-240v, 50/60hz',
            revolutionsPerMinute: '7200',
            hardwareInterface: 'SATA 6.0 Gb/s',
            readSpeed: '140 MBs',
            writeSpeed: '140',
            cacheSize: '128',
            warranty: '24 months',
            compatibleDevices: 'Desktop',
            SATAcableIncluded: 'Yes'
        },

        {
            name: 'Western Digital 12TB HDD',
            brand: 'Western Digital',
            productDimensions: '14.68 x 10.16 x 2.59 cm; 662.24 Grams',
            itemModelNumber: 'WD121KRYZ',
            manufacturer: 'Western Digital',
            series: 'Western Digital',
            color: 'Silver',
            formFactor: '3.5"',
            hardDriveSize: '12 TB',
            hardDiskDescription: 'HDD',
            wattage: '10',
            powerSource: 'System powered',
            revolutionsPerMinute: '7200',
            hardwareInterface: 'SATA 6.0 Gb/s',
            readSpeed: '140 MBs',
            writeSpeed: '140',
            cacheSize: '256',
            warranty: '24 months',
            compatibleDevices: 'Desktop',
            SATAcableIncluded: 'Yes'
        },

        // HSF

        // {
        //     name: '',
        //     brand: '',
        //     productDimensions: '',
        //     itemModelNumber: '',
        //     manufacturer: '',
        //     series: '',
        //     color: '',
        //     intelCPUsocket: '',
        //     amdCPUsocket: '',
        //     heatsink: '',
        //     wattage: '',
        //     LED: '',
        //     fanSpeed: '',
        //     fanNoiseLevel: '',
        //     coolingType: '',
        //     compatibleDevices: '',
        //     material: '',
        //     thermalPasteIncluded: '',
        //     warranty: '',
        //     itemWeight: '',
        // },

        {
            name: 'Gammaxx 400',
            brand: 'DEEP COOL',
            productDimensions: '16.51 x 17.53 x 12.19 cm; 680.39 Grams',
            itemModelNumber: 'GAMMAXX400V2RED-EU',
            manufacturer: 'Deepcool',
            series: 'GAMMAXX 400',
            color: 'Black',
            intelCPUsocket: 'LGA2011/1366/1156/1155/1150/775',
            amdCPUsocket: 'FM2/FM1/AM3+/AM3/AM2+/AM2/K8/AM4',
            heatsink: '4 heatpipes',
            wattage: '3',
            LED: 'Blue LED fan',
            fanSpeed: 'PWM: 900±150-1500±10%RPM',
            fanNoiseLevel: '26.1 dB',
            coolingType: 'Fan',
            compatibleDevices: 'Desktop',
            material: 'Copper',
            thermalPasteIncluded: 'Yes',
            warranty: '24 Months',
            itemWeight: '680g',
        },
        {
            name: 'H115i',
            brand: 'Corsair',
            productDimensions: '32 x 14 x 3 cm; 980 Grams',
            itemModelNumber: 'CW-9060044-WW',
            manufacturer: 'Corsair',
            series: 'WATER COOLING CORSAIR H115I RGB PRO XT *CW-9060044-WW*6689',
            color: 'RGB',
            intelCPUsocket: 'LGA2011/1366/1156/1155/1150/775',
            amdCPUsocket: 'FM2/FM1/AM3+/AM3/AM2+/AM2/K8/AM4',
            heatsink: '4 heatpipes',
            wattage: '5',
            LED: 'RGB',
            fanSpeed: 'PWM: 900±150-1500±10%RPM',
            fanNoiseLevel: '25 dB',
            coolingType: 'Water',
            compatibleDevices: 'Desktop',
            material: 'Copper',
            thermalPasteIncluded: 'Yes',
            warranty: '24 Months',
            itemWeight: '980g',
        },
        {
            name: 'Celsius S24',
            brand: 'Fractal Design',
            productDimensions: '28.4 x 12.2 x 3.1 cm; 1.8 Kilograms',
            itemModelNumber: 'FD-WCU-CELSIUS-S24-BKO',
            manufacturer: 'FRACTAL DESIGN',
            series: 'WATER FRACTAL CELSIUS S24 BLACKOUT (FD-WCU-CELSIUS-S24-BKO) 1859',
            color: 'Blackout',
            intelCPUsocket: 'LGA2011/1366/1156/1155/1150/775',
            amdCPUsocket: 'FM2/FM1/AM3+/AM3/AM2+/AM2/K8/AM4',
            heatsink: '4 heatpipes',
            wattage: '5',
            LED: 'RGB',
            fanSpeed: 'PWM: 900±150-1500±10%RPM',
            fanNoiseLevel: '30 dB',
            coolingType: 'Water',
            compatibleDevices: 'Desktop',
            material: 'Copper',
            thermalPasteIncluded: 'Yes',
            warranty: '24 Months',
            itemWeight: '1.8kg',
        },
        {
            name: 'CLC 280',
            brand: 'EVGA',
            productDimensions: '17.78 x 35.56 x 19.56 cm; 1.18 Kilograms',
            itemModelNumber: '400-HY-CL28-V1',
            manufacturer: 'EVGA',
            series: 'EVGA 400-HY-CL28-V1',
            color: 'Black',
            intelCPUsocket: 'LGA2011/1366/1156/1155/1150/775',
            amdCPUsocket: 'FM2/FM1/AM3+/AM3/AM2+/AM2/K8/AM4',
            heatsink: '4 heatpipes',
            wattage: '125',
            LED: 'RGB',
            fanSpeed: 'PWM: 900±150-1500±10%RPM',
            fanNoiseLevel: '39.5 dB',
            coolingType: 'Water',
            compatibleDevices: 'Desktop',
            material: 'Copper',
            thermalPasteIncluded: 'Yes',
            warranty: '24 Months',
            itemWeight: '1.18kg',
        },
        {
            name: 'Dark Rock 4',
            brand: 'Be Quiet',
            productDimensions: '9.4 x 13.59 x 15.95 cm; 920 Grams',
            itemModelNumber: 'BK021',
            manufacturer: 'BE QUIET',
            series: 'Dark Rock 4',
            color: 'Black',
            intelCPUsocket: 'LGA2011/1366/1156/1155/1150/775',
            amdCPUsocket: 'FM2/FM1/AM3+/AM3/AM2+/AM2/K8/AM4',
            heatsink: '4 heatpipes',
            wattage: '125',
            LED: 'RGB',
            fanSpeed: 'PWM: 900±150-1500±10%RPM',
            fanNoiseLevel: '21.4 dB',
            coolingType: 'Fan',
            compatibleDevices: 'Desktop',
            material: 'Copper',
            thermalPasteIncluded: 'Yes',
            warranty: '24 Months',
            itemWeight: '920g',
        },
        {
            name: 'Dark Rock Pro 4',
            brand: 'Be Quiet',
            productDimensions: '13.6 x 14.57 x 162.8 cm; 1.13 Kilograms',
            itemModelNumber: 'BK022',
            manufacturer: 'Be Quiet',
            series: 'Dark Rock Pro 4',
            color: 'Black',
            intelCPUsocket: 'LGA2011/1366/1156/1155/1150/775',
            amdCPUsocket: 'FM2/FM1/AM3+/AM3/AM2+/AM2/K8/AM4',
            heatsink: '4 heatpipes',
            wattage: '125',
            LED: 'RGB',
            fanSpeed: 'PWM: 900±150-1500±10%RPM',
            fanNoiseLevel: '24.3 dB',
            coolingType: 'Fan',
            compatibleDevices: 'Desktop',
            material: 'Copper',
            thermalPasteIncluded: 'Yes',
            warranty: '24 Months',
            itemWeight: '1.13kg',
        },
        {
            name: 'NH_U12S AM4',
            brand: 'Noctua',
            productDimensions: '12.5 x 7.1 x 15.8 cm; 800 Grams',
            itemModelNumber: 'NH-U12S SE-AM4',
            manufacturer: 'Noctua',
            series: 'NH-U12S SE-AM4 Special Edition',
            color: 'Brown',
            intelCPUsocket: 'LGA2011/1366/1156/1155/1150/775',
            amdCPUsocket: 'FM2/FM1/AM3+/AM3/AM2+/AM2/K8/AM4',
            heatsink: '4 heatpipes',
            wattage: '12',
            LED: 'RGB',
            fanSpeed: 'PWM: 900±150-1500±10%RPM',
            fanNoiseLevel: '22.4 dB',
            coolingType: 'Fan',
            compatibleDevices: 'Desktop',
            material: 'Copper (base and heat-pipes), aluminium (cooling fins), soldered joints & nickel plating',
            thermalPasteIncluded: 'Yes',
            warranty: '24 Months',
            itemWeight: '800g',
        },
        {
            name: 'Pure Rock 2',
            brand: 'Be Quiet',
            productDimensions: '12 x 12 x 2.5 cm; 575 Grams',
            itemModelNumber: 'BK007',
            manufacturer: 'BE QUIET',
            series: 'Pure Rock 2 Black',
            color: 'Black',
            intelCPUsocket: 'LGA2011/1366/1156/1155/1150/775',
            amdCPUsocket: 'FM2/FM1/AM3+/AM3/AM2+/AM2/K8/AM4',
            heatsink: '4 heatpipes',
            wattage: '150',
            LED: 'N/A',
            fanSpeed: 'PWM: 900±150-1500±10%RPM',
            fanNoiseLevel: '26.8 dB',
            coolingType: 'Thermal',
            compatibleDevices: 'Desktop',
            material: 'Copper',
            thermalPasteIncluded: 'Yes',
            warranty: '24 Months',
            itemWeight: '575g',
        },
        {
            name: '212 Black',
            brand: 'Cooler Master',
            productDimensions: '12 x 7.96 x 15.88 cm; 850 Grams',
            itemModelNumber: 'RR-212S-20PK-R1',
            manufacturer: 'Cooler Master',
            series: 'RR-212S-20PK-R1 RR-212S',
            color: 'Black',
            intelCPUsocket: 'LGA2011/1366/1156/1155/1150/775',
            amdCPUsocket: 'FM2/FM1/AM3+/AM3/AM2+/AM2/K8/AM4',
            heatsink: '3 heatpipes',
            wattage: '12',
            LED: 'RGB',
            fanSpeed: 'PWM: 800±150-2200±10%RPM',
            fanNoiseLevel: '26 dB',
            coolingType: 'Fan',
            compatibleDevices: 'Desktop',
            material: 'Aluminium, Copper',
            thermalPasteIncluded: 'Yes',
            warranty: '24 Months',
            itemWeight: '850g',
        },
        {
            name: 'Freezer 34 Duo',
            brand: 'Arctic',
            productDimensions: '12.3 x 10.3 x 15 cm; 200 Grams',
            itemModelNumber: 'ACFRE00061A',
            manufacturer: 'ARCTIC',
            series: 'Freezer 34 eSports DUO',
            color: 'White',
            intelCPUsocket: 'LGA2011/1366/1156/1155/1150/775',
            amdCPUsocket: 'FM2/FM1/AM3+/AM3/AM2+/AM2/K8/AM4',
            heatsink: '3 heatpipes',
            wattage: '12',
            LED: 'RGB',
            fanSpeed: 'PWM: 200±150-2100±10%RPM',
            fanNoiseLevel: '0.5 Sones',
            coolingType: 'Other',
            compatibleDevices: 'Desktop',
            material: 'Copper',
            thermalPasteIncluded: 'Yes',
            warranty: '24 Months',
            itemWeight: '200g',
        },


        // Motherboards

        // {
        //     name: '',
        //     brand: '',
        //     productDimensions: '',
        //     batteries: '',
        //     itemModelNumber: '',
        //     manufacturer: '',
        //     series: '',
        //     color: '',
        //     formFactor: '',
        //     processorSocket: '',
        //     memoryTechnology: '',
        //     computerMemoryType: '',
        //     maximumMemorySupported: '',
        //     graphicsChipsetBrand: '',
        //     graphicsCardDescription: '',
        //     graphicsCardInterface: '',
        //     connectivityType: '',
        //     wirelessType: '',
        //     numberOfUSBports: '',
        //     numberOfHDMIports: ''
        // },
        {
            name: 'ASRock A320M-HDV',
            brand: 'ASRock',
            productDimensions: '6 x 25.4 x 28.6 cm; 250 Grams',
            batteries: '1 CR2 batteries required. (included)',
            itemModelNumber: 'A320M-HDV R4.0',
            manufacturer: 'ASROCK',
            series: 'A320M-HDV R4.0',
            color: 'Multi-coloured',
            formFactor: 'Micro ATX',
            processorSocket: 'Socket AM4',
            memoryTechnology: 'DDR4',
            computerMemoryType: 'DDR4 SDRAM',
            maximumMemorySupported: '32 GB',
            graphicsChipsetBrand: 'AMD',
            graphicsCardDescription: 'AMD',
            graphicsCardInterface: 'PCI-E',
            connectivityType: 'No',
            wirelessType: '802.11a',
            numberOfUSBports: '2',
            numberOfHDMIports: '1'
        },
        {
            name: 'MSI B450-A Pro',
            brand: 'MSI',
            productDimensions: '30.5 x 24.4 x 3 cm; 1 Kilograms',
            batteries: 'Not Included',
            itemModelNumber: 'B450-A PRO MAX',
            manufacturer: 'MSI COMPUTER',
            series: 'MSI B450-A PRO MAX',
            formFactor: 'ATX',
            processorSocket: 'LGA 1150',
            memoryTechnology: 'DDR4',
            computerMemoryType: 'DDR4 SDRAM',
            maximumMemorySupported: '1 GB',
            graphicsCardInterface: 'PCI-E',
            numberOfUSBports: '2'
        },
        {
            name: 'MSI B450M Pro',
            brand: 'MSI',
            productDimensions: '30.5 x 24.4 x 3 cm; 690 Grams',
            itemModelNumber: 'B450M PRO-VDH MAX',
            manufacturer: 'MSI COMPUTER',
            series: 'MSI B450M PRO-VDH MAX',
            formFactor: 'Micro ATX',
            processorSocket: 'LGA 1150',
            memoryTechnology: 'DDR4',
            graphicsCardInterface: 'PCI-E',
            connectivityType: 'Yes',
            numberOfUSBports: '4'
        },
        {
            name: 'MSI TRX40 Pro',
            brand: 'MSI',
            productDimensions: '30.4 x 24.4 x 5 cm; 2.79 Kilograms',
            itemModelNumber: '133546',
            manufacturer: 'MSI COMPUTER',
            series: 'TRX40 PRO 10G',
            formFactor: 'ATX',
            processorSocket: 'LGA 775',
            memoryTechnology: 'DDR5 RAM',
            maximumMemorySupported: '256 GB',
            graphicsCardInterface: 'PCI-E',
            connectivityType: 'Yes',
            wirelessType: '802.11a'
        },
        {
            name: 'Gigabyte TRX40 Pro',
            brand: 'Gigabyte',
            productDimensions: '17 x 17 x 4 cm; 230 Grams',
            battery: '1 Lithium ion batteries required. (included)',
            itemModelNumber: 'B550I AORUS PRO AX',
            manufacturer: 'Gigabyte',
            formFactor: 'Mini ITX',
            processorSocket: 'Socket AM4',
            memoryTechnology: 'DDR4',
            graphicsCardInterface: 'PCI-E',
            wirelessType: '802.11ax'
        },
        {
            name: 'ASUS TRX40-Pro',
            brand: 'ASUS',
            productDimensions: '24.4 x 24.4 x 4.5 cm; 2.1 Kilograms',
            itemModelNumber: 'PRIME TRX40 PRO',
            manufacturer: 'Asus',
            series: 'PRIME TRX40 PRO',
            formFactor: 'ATX',
            processorSocket: 'LGA 775',
            memoryTechnology: 'DDR5 RAM',
            computerMemoryType: 'DRAM',
            graphicsCardInterface: 'PCI-Express x16',
            wirelessType: '802.11a',
            numberOfUSBports: '4',
            numberOfHDMIports: '1'
        },
        {
            name: 'Gigabyte X570 UD',
            brand: 'Gigabyte',
            productDimensions: '30.5 x 24.4 x 4 cm; 970 Grams',
            itemModelNumber: 'X570 UD',
            manufacturer: 'Gigabyte',
            series: 'X570 UD',
            formFactor: 'ATX',
            processorSocket: 'Socket AM4',
            memoryTechnology: 'DDR4',
            graphicsCardInterface: 'PCI-E',
            connectivityType: 'Yes',
            numberOfUSBports: '2',
        },
        {
            name: 'ASRock X570 Gaming 4',
            brand: 'ASRock',
            productDimensions: '34.54 x 7.62 x 28.19 cm; 1.2 Kilograms',
            itemModelNumber: 'X570 Phantom Gaming 4',
            manufacturer: 'ASROCK',
            formFactor: 'ATX',
            processorSocket: 'AM4',
            memoryTechnology: 'DDR4',
            computerMemoryType: 'DDR4 SDRAM',
            maximumMemorySupported: '128 GB',
            graphicsCardInterface: 'PCI-E',
            numberOfUSBports: '1'
        },
        {
            name: 'Gigabyte A520M DS3H',
            brand: 'Gigabyte',
            productDimensions: '26.49 x 26.49 x 5.38 cm; 501.54 Grams',
            itemModelNumber: 'A520M-DS3H',
            manufacturer: 'Gigabyte',
            formFactor: 'Micro ATX',
            processorSocket: 'Socket AM4',
            memoryTechnology: 'DDR4',
            graphicsCardInterface: 'PCI-E',
            numberOfUSBports: '2',
            numberOfHDMIports: '1'
        },
        {
            name: 'ASRock B450M-HDV',
            brand: 'ASRock',
            productDimensions: '30.48 x 6.35 x 24.38 cm; 730 Grams',
            batteries: '1 Lithium Metal batteries required.',
            itemModelNumber: 'B450M-HDV R4.0',
            manufacturer: 'ASRock',
            series: 'B450M-HDV R4.0',
            formFactor: 'Micro ATX',
            processorSocket: 'Socket AM4',
            memoryTechnology: 'DDR4',
            computerMemoryType: 'DDR4 SDRAM',
            maximumMemorySupported: '32 GB',
            graphicsCardInterface: 'PCI-E',
            connectivityType: 'Yes',
            wirelessType: '802.11a',
            numberOfUSBports: '2',
            numberOfHDMIports: '1'
        },
        {
            name: 'MSI X570-A Pro',
            brand: 'MSI',
            productDimensions: '34.6 x 26.9 x 6.5 cm; 1.1 Kilograms',
            itemModelNumber: '7C37-003R',
            manufacturer: 'MSI COMPUTER',
            series: 'MSI AMD X570-A PRO D4 ATX Motherboard',
            formFactor: 'ATX',
            processorSocket: 'Socket AM4',
            memoryTechnology: 'DDR4',
            computerMemoryType: 'DDR4 SDRAM',
            maximumMemorySupported: '128 GB',
            graphicsCardInterface: 'PCI-E',
            numberOfUSBports: '2'
        },
        {
            name: 'MSI B450 Gaming Plus',
            brand: 'MSI',
            productDimensions: '30.5 x 24 x 3 cm; 1.2 Kilograms',
            itemModelNumber: 'B450 GAMING PLUS MAX',
            manufacturer: 'MSI COMPUTER',
            series: 'MSI B450 GAMING PLUS MAX',
            formFactor: 'ATX',
            processorSocket: 'LGA 1150',
            memoryTechnology: 'DDR4',
            computerMemoryType: 'DDR4 SDRAM',
            maximumMemorySupported: '32 GB',
            numberOfUSBports: '2',
        },
        {
            name: 'ASUS X570-Plus',
            brand: 'ASUS',
            productDimensions: '30.5 x 24.4 x 5.5 cm; 400 Grams',
            batteries: '1 Lithium Metal batteries required. (included)',
            itemModelNumber: '90MB1180-M0EAY0',
            manufacturer: 'Asus',
            series: 'Asus AMD TUF Gaming X570-Plus Motherboard',
            color: 'Black',
            formFactor: 'ATX',
            processorSocket: 'Socket AM4',
            memoryTechnology: 'DDR4',
            computerMemoryType: 'DDR4 SDRAM',
            graphicsCardInterface: 'PCI-E',
            connectivityType: 'Yes',
            numberOfUSBports: '4',
            numberOfHDMIports: '1'
        },
        {
            name: 'ASUS X570-F',
            brand: 'ASUS',
            productDimensions: '30.5 x 24.4 x 5.5 cm; 400 Grams',
            batteries: '1 Lithium Metal batteries required. (included)',
            itemModelNumber: '90MB1180-M0EAY0',
            manufacturer: 'Asus',
            series: 'Asus AMD TUF Gaming X570-Plus Motherboard',
            color: 'Black',
            formFactor: 'ATX',
            processorSocket: 'Socket AM4',
            memoryTechnology: 'DDR4',
            computerMemoryType: 'DDR4 SDRAM',
            graphicsCardInterface: 'PCI-E',
            connectivityType: 'Yes',
            numberOfUSBports: '4',
        },
        {
            name: 'ASUS X570-Pro',
            brand: 'ASUS',
            productDimensions: '30.5 x 24.4 x 5.5 cm; 400 Grams',
            batteries: '1 Lithium Metal batteries required. (included)',
            itemModelNumber: '90MB1180-M0EAY0',
            manufacturer: 'Asus',
            series: 'Asus AMD TUF Gaming X570-Plus Motherboard',
            color: 'Black',
            formFactor: 'ATX',
            processorSocket: 'Socket AM4',
            memoryTechnology: 'DDR4',
            computerMemoryType: 'DDR4 SDRAM',
            graphicsCardInterface: 'PCI-E',
            numberOfUSBports: '2',
            numberOfHDMIports: '1'
        },
        {
            name: 'ASUS X570-P',
            brand: 'ASUS',
            productDimensions: '30.5 x 24.4 x 4.5 cm; 400 Grams',
            itemModelNumber: '90MB11N0-M0EAY0',
            manufacturer: 'Asus',
            series: 'Asus AMD Prime X570-P Motherboard',
            color: 'Black',
            formFactor: 'ATX',
            processorSocket: 'Socket AM4',
            memoryTechnology: 'DDR4',
            computerMemoryType: 'DDR4 SDRAM',
            graphicsCardInterface: 'PCI-E',
            connectivityType: 'No',
            numberOfUSBports: '2',
            numberOfHDMIports: '1'
        },
        {
            name: 'ASRock X570 Steel',
            brand: 'ASRock',
            productDimensions: '38.35 x 8.64 x 33.27 cm; 1.3 Kilograms',
            itemModelNumber: 'X570 Steel Legend',
            manufacturer: 'ASRock',
            formFactor: 'ATX',
            processorSocket: 'Socket AM4',
            memoryTechnology: 'DDR4',
            computerMemoryType: 'DDR4 SDRAM',
            maximumMemorySupported: '128GB',
            graphicsCardInterface: 'PCI-E',
            numberOfUSBports: '4',
            numberOfHDMIports: '1'
        },
        {
            name: 'Gigabyte X570 ULTRA',
            brand: 'Gigabyte',
            productDimensions: '30.5 x 24.4 x 4 cm; 1.7 Kilograms',
            batteries: '1 Lithium ion batteries required. (included)',
            itemModelNumber: 'X570 AORUS ULTRA',
            manufacturer: 'Gigabyte',
            series: 'X570 AORUS ULTRA',
            formFactor: 'ATX',
            processorSocket: 'Socket AM4',
            memoryTechnology: 'DDR4',
            computerMemoryType: 'DDR4 SDRAM',
            graphicsCardInterface: 'PCI-E',
            connectivityType: 'No',
            wirelessType: '802.11a/b/g/n',
            numberOfUSBports: '4',
        },
        {
            name: 'Gigabyte X570 ELITE',
            brand: 'Gigabyte',
            productDimensions: '30.5 x 24.4 x 4 cm; 1.5 Kilograms',
            batteries: '1 Lithium ion batteries required. (included)',
            itemModelNumber: 'X570 AORUS ELITE',
            manufacturer: 'Gigabyte',
            series: 'X570 AORUS ELITE',
            formFactor: 'ATX',
            processorSocket: 'Socket AM4',
            maximumMemorySupported: '128 GB',
            graphicsCardInterface: 'PCI-E',
            numberOfUSBports: '2',
            numberOfHDMIports: '1'
        },

        // PSU

        // {
        //     name: '',
        //     brand: '',
        //     productDimensions: '',
        //     outputWattage: '',
        //     inputWattage: '',
        //     itemModelNumber: '',
        //     manufacturer: '',
        //     series: '',
        //     color: '',
        //     formFactor: '',
        //     powerSupplyDesign: '',
        //     efficiency: '',
        //     voltage: '',
        //     operatingTemperature: '',
        //     batteriesIncluded: '',
        //     fanBearing: '',
        //     fanControl: '',
        //     cableFree: '',
        //     warranty: '',
        //     itemWeight: ''
        // },
        {
            name: 'PRIME Platinum 1000W',
            brand: 'Seasonic',
            productDimensions: '34.3 x 14 x 20.3 centimetres',
            outputWattage: '1000',
            inputWattage: '125',
            itemModelNumber: 'SSR-1000GD',
            manufacturer: 'Seasonic',
            series: 'PRIME Ultra Gold',
            color: 'Gold',
            formFactor: 'ATX',
            powerSupplyDesign: 'Full Modular',
            efficiency: 'Platinum',
            voltage: '12',
            operatingTemperature: '50',
            batteriesIncluded: 'No',
            fanBearing: 'Sleeve',
            fanControl: 'Premium Hybrid',
            cableFree: 'Yes',
            warranty: '24 Months',
            itemWeight: '2.04Kg'
        },
        {
            name: 'Corsair RM 750x Gold',
            brand: 'Corsair',
            productDimensions: '34.3 x 14 x 20.3 centimetres',
            outputWattage: '1000',
            inputWattage: '125',
            itemModelNumber: 'SSR-1000GD',
            manufacturer: 'Seasonic',
            series: 'PRIME Ultra Gold',
            color: 'Gold',
            formFactor: 'ATX',
            powerSupplyDesign: 'Full Modular',
            efficiency: 'Platinum',
            voltage: '12',
            operatingTemperature: '50',
            batteriesIncluded: 'No',
            fanBearing: 'Sleeve',
            fanControl: 'Premium Hybrid',
            cableFree: 'Yes',
            warranty: '24 Months',
            itemWeight: '2.04Kg'
        },
        {
            name: 'Corsair RM 750 Gold',
            brand: 'Corsair',
            productDimensions: '34.3 x 14 x 20.3 centimetres',
            outputWattage: '1000',
            inputWattage: '125',
            itemModelNumber: 'SSR-1000GD',
            manufacturer: 'Seasonic',
            series: 'PRIME Ultra Gold',
            color: 'Gold',
            formFactor: 'ATX',
            powerSupplyDesign: 'Full Modular',
            efficiency: 'Platinum',
            voltage: '12',
            operatingTemperature: '50',
            batteriesIncluded: 'No',
            fanBearing: 'Sleeve',
            fanControl: 'Premium Hybrid',
            cableFree: 'Yes',
            warranty: '24 Months',
            itemWeight: '2.04Kg'
        },
        {
            name: 'EVGA 650W Gold',
            brand: 'EVGA',
            productDimensions: '34.3 x 14 x 20.3 centimetres',
            outputWattage: '1000',
            inputWattage: '125',
            itemModelNumber: 'SSR-1000GD',
            manufacturer: 'Seasonic',
            series: 'PRIME Ultra Gold',
            color: 'Gold',
            formFactor: 'ATX',
            powerSupplyDesign: 'Full Modular',
            efficiency: 'Platinum',
            voltage: '12',
            operatingTemperature: '50',
            batteriesIncluded: 'No',
            fanBearing: 'Sleeve',
            fanControl: 'Premium Hybrid',
            cableFree: 'Yes',
            warranty: '24 Months',
            itemWeight: '2.04Kg'
        },
        {
            name: 'EVGA 850W Gold',
            brand: 'EVGA',
            productDimensions: '34.3 x 14 x 20.3 centimetres',
            outputWattage: '1000',
            inputWattage: '125',
            itemModelNumber: 'SSR-1000GD',
            manufacturer: 'Seasonic',
            series: 'PRIME Ultra Gold',
            color: 'Gold',
            formFactor: 'ATX',
            powerSupplyDesign: 'Full Modular',
            efficiency: 'Platinum',
            voltage: '12',
            operatingTemperature: '50',
            batteriesIncluded: 'No',
            fanBearing: 'Sleeve',
            fanControl: 'Premium Hybrid',
            cableFree: 'Yes',
            warranty: '24 Months',
            itemWeight: '2.04Kg'
        },
        {
            name: 'FOCUS 750W Platinum',
            brand: 'Seasonic',
            productDimensions: '34.3 x 14 x 20.3 centimetres',
            outputWattage: '1000',
            inputWattage: '125',
            itemModelNumber: 'SSR-1000GD',
            manufacturer: 'Seasonic',
            series: 'PRIME Ultra Gold',
            color: 'Gold',
            formFactor: 'ATX',
            powerSupplyDesign: 'Full Modular',
            efficiency: 'Platinum',
            voltage: '12',
            operatingTemperature: '50',
            batteriesIncluded: 'No',
            fanBearing: 'Sleeve',
            fanControl: 'Premium Hybrid',
            cableFree: 'Yes',
            warranty: '24 Months',
            itemWeight: '2.04Kg'
        },
        {
            name: 'PRO SERIES 850W Platinum',
            brand: 'Corsair',
            productDimensions: '34.3 x 14 x 20.3 centimetres',
            outputWattage: '1000',
            inputWattage: '125',
            itemModelNumber: 'SSR-1000GD',
            manufacturer: 'Seasonic',
            series: 'PRIME Ultra Gold',
            color: 'Gold',
            formFactor: 'ATX',
            powerSupplyDesign: 'Full Modular',
            efficiency: 'Platinum',
            voltage: '12',
            operatingTemperature: '50',
            batteriesIncluded: 'No',
            fanBearing: 'Sleeve',
            fanControl: 'Premium Hybrid',
            cableFree: 'Yes',
            warranty: '24 Months',
            itemWeight: '2.04Kg'
        },
        {
            name: 'PRO SERIES 1000W Platinum',
            brand: 'Corsair',
            productDimensions: '34.3 x 14 x 20.3 centimetres',
            outputWattage: '1000',
            inputWattage: '125',
            itemModelNumber: 'SSR-1000GD',
            manufacturer: 'Seasonic',
            series: 'PRIME Ultra Gold',
            color: 'Gold',
            formFactor: 'ATX',
            powerSupplyDesign: 'Full Modular',
            efficiency: 'Platinum',
            voltage: '12',
            operatingTemperature: '50',
            batteriesIncluded: 'No',
            fanBearing: 'Sleeve',
            fanControl: 'Premium Hybrid',
            cableFree: 'Yes',
            warranty: '24 Months',
            itemWeight: '2.04Kg'
        },
        {
            name: 'Seasonic 550W Bronze',
            brand: 'Seasonic',
            productDimensions: '34.3 x 14 x 20.3 centimetres',
            outputWattage: '1000',
            inputWattage: '125',
            itemModelNumber: 'SSR-1000GD',
            manufacturer: 'Seasonic',
            series: 'PRIME Ultra Gold',
            color: 'Gold',
            formFactor: 'ATX',
            powerSupplyDesign: 'Full Modular',
            efficiency: 'Platinum',
            voltage: '12',
            operatingTemperature: '50',
            batteriesIncluded: 'No',
            fanBearing: 'Sleeve',
            fanControl: 'Premium Hybrid',
            cableFree: 'Yes',
            warranty: '24 Months',
            itemWeight: '2.04Kg'
        },
        {
            name: 'FOCUS 850W Platinum',
            brand: 'Seasonic',
            productDimensions: '34.3 x 14 x 20.3 centimetres',
            outputWattage: '1000',
            inputWattage: '125',
            itemModelNumber: 'SSR-1000GD',
            manufacturer: 'Seasonic',
            series: 'PRIME Ultra Gold',
            color: 'Gold',
            formFactor: 'ATX',
            powerSupplyDesign: 'Full Modular',
            efficiency: 'Platinum',
            voltage: '12',
            operatingTemperature: '50',
            batteriesIncluded: 'No',
            fanBearing: 'Sleeve',
            fanControl: 'Premium Hybrid',
            cableFree: 'Yes',
            warranty: '24 Months',
            itemWeight: '2.04Kg'
        },
        {
            name: 'Seasonic 650W Bronze',
            brand: 'Seasonic',
            productDimensions: '34.3 x 14 x 20.3 centimetres',
            outputWattage: '1000',
            inputWattage: '125',
            itemModelNumber: 'SSR-1000GD',
            manufacturer: 'Seasonic',
            series: 'PRIME Ultra Gold',
            color: 'Gold',
            formFactor: 'ATX',
            powerSupplyDesign: 'Full Modular',
            efficiency: 'Platinum',
            voltage: '12',
            operatingTemperature: '50',
            batteriesIncluded: 'No',
            fanBearing: 'Sleeve',
            fanControl: 'Premium Hybrid',
            cableFree: 'Yes',
            warranty: '24 Months',
            itemWeight: '2.04Kg'
        },
        {
            name: 'Seasonic 1000W Titanium',
            brand: 'Seasonic',
            productDimensions: '34.3 x 14 x 20.3 centimetres',
            outputWattage: '1000',
            inputWattage: '125',
            itemModelNumber: 'SSR-1000GD',
            manufacturer: 'Seasonic',
            series: 'PRIME Ultra Gold',
            color: 'Gold',
            formFactor: 'ATX',
            powerSupplyDesign: 'Full Modular',
            efficiency: 'Platinum',
            voltage: '12',
            operatingTemperature: '50',
            batteriesIncluded: 'No',
            fanBearing: 'Sleeve',
            fanControl: 'Premium Hybrid',
            cableFree: 'Yes',
            warranty: '24 Months',
            itemWeight: '2.04Kg'
        },

        // RAM

        // {
        //     name: '',
        //     brand: '',
        //     productDimensions: '',
        //     itemModelNumber: '',
        //     manufacturer: '',
        //     series: '',
        //     color: '',
        //     processorCount: '',
        //     RAMsize: '',
        //     memoryTechnology: '',
        //     computerMemoryType: '',
        //     memoryClockSpeed: '',
        //     size: '',
        //     voltage: '',
        //     memorySpeed: '',
        //     modelYear: '',
        //     operatingSystem: '',
        //     batteriesIncluded: '',
        //     warranty: '',
        //     itemWeight: ''
        // },
        {
            name: 'VENGEANCE 16GB DDR4',
            brand: 'Corsair',
            productDimensions: '17.12 x 9.02 x 1.55 cm; 90.72 Grams',
            itemModelNumber: 'CMK16GX4M2B3000C15',
            manufacturer: 'Corsair',
            series: 'CMK16GX4M2B3000C15',
            color: 'Black',
            processorCount: '1',
            RAMsize: '16 GB',
            memoryTechnology: 'DDR4',
            computerMemoryType: 'DDR4 SDRAM',
            memoryClockSpeed: '2',
            size: '8 GB',
            voltage: '1.35',
            memorySpeed: '2666 MHz',
            modelYear: '2015',
            operatingSystem: 'Microsoft',
            batteriesIncluded: 'No',
            warranty: '24 months',
            itemWeight: '90.7g'
        },
        {
            name: 'VENGEANCE 32GB DDR4',
            brand: 'Corsair',
            productDimensions: '17.12 x 9.02 x 1.55 cm; 90.72 Grams',
            itemModelNumber: 'CMK16GX4M2B3000C15',
            manufacturer: 'Corsair',
            series: 'CMK16GX4M2B3000C15',
            color: 'Black',
            processorCount: '1',
            RAMsize: '16 GB',
            memoryTechnology: 'DDR4',
            computerMemoryType: 'DDR4 SDRAM',
            memoryClockSpeed: '2',
            size: '8 GB',
            voltage: '1.35',
            memorySpeed: '2666 MHz',
            modelYear: '2015',
            operatingSystem: 'Microsoft',
            batteriesIncluded: 'No',
            warranty: '24 months',
            itemWeight: '90.7g'
        },
        {
            name: 'Crucial RAM 4 GB DDR4',
            brand: 'Corsair',
            productDimensions: '17.12 x 9.02 x 1.55 cm; 90.72 Grams',
            itemModelNumber: 'CMK16GX4M2B3000C15',
            manufacturer: 'Corsair',
            series: 'CMK16GX4M2B3000C15',
            color: 'Black',
            processorCount: '1',
            RAMsize: '16 GB',
            memoryTechnology: 'DDR4',
            computerMemoryType: 'DDR4 SDRAM',
            memoryClockSpeed: '2',
            size: '8 GB',
            voltage: '1.35',
            memorySpeed: '2666 MHz',
            modelYear: '2015',
            operatingSystem: 'Microsoft',
            batteriesIncluded: 'No',
            warranty: '24 months',
            itemWeight: '90.7g'
        },
        {
            name: 'FURY Black 8 GB DDR4',
            brand: 'Corsair',
            productDimensions: '17.12 x 9.02 x 1.55 cm; 90.72 Grams',
            itemModelNumber: 'CMK16GX4M2B3000C15',
            manufacturer: 'Corsair',
            series: 'CMK16GX4M2B3000C15',
            color: 'Black',
            processorCount: '1',
            RAMsize: '16 GB',
            memoryTechnology: 'DDR4',
            computerMemoryType: 'DDR4 SDRAM',
            memoryClockSpeed: '2',
            size: '8 GB',
            voltage: '1.35',
            memorySpeed: '2666 MHz',
            modelYear: '2015',
            operatingSystem: 'Microsoft',
            batteriesIncluded: 'No',
            warranty: '24 months',
            itemWeight: '90.7g'
        },
        {
            name: 'Viper Steel 64GB DDR4',
            brand: 'Corsair',
            productDimensions: '17.12 x 9.02 x 1.55 cm; 90.72 Grams',
            itemModelNumber: 'CMK16GX4M2B3000C15',
            manufacturer: 'Corsair',
            series: 'CMK16GX4M2B3000C15',
            color: 'Black',
            processorCount: '1',
            RAMsize: '16 GB',
            memoryTechnology: 'DDR4',
            computerMemoryType: 'DDR4 SDRAM',
            memoryClockSpeed: '2',
            size: '8 GB',
            voltage: '1.35',
            memorySpeed: '2666 MHz',
            modelYear: '2015',
            operatingSystem: 'Microsoft',
            batteriesIncluded: 'No',
            warranty: '24 months',
            itemWeight: '90.7g'
        },

        // SSD

        // {
        //     name: '',
        //     brand: '',
        //     productDimensions: '',
        //     itemModelNumber: '',
        //     manufacturer: '',
        //     series: '',
        //     color: '',
        //     formFactor: '',
        //     hardDriveSize: '',
        //     hardDiskDescription: '',
        //     wattage: '',
        //     powerSource: '',
        //     revolutionsPerMinute: '',
        //     hardwareInterface: '',
        //     readSpeed: '',
        //     writeSpeed: '',
        //     cacheSize: '',
        //     warranty: '',
        //     compatibleDevices: '',
        //     SATAcableIncluded: ''
        // },

        {
            name: 'ADATA 2TB SSD',
            brand: 'ADATA',
            productDimensions: '7.9 x 2.5 x 2.3 cm; 30 Grams',
            itemModelNumber: 'ASX8200PNP-512GT-C',
            manufacturer: 'ADATA',
            series: 'XPG SX8200 Pro',
            color: 'Silver',
            formFactor: '',
            hardDriveSize: '2 TB',
            hardDiskDescription: 'Solid State Hard Drive',
            wattage: '23',
            powerSource: 'System Powered',
            revolutionsPerMinute: '2280',
            hardwareInterface: 'SATA 6.0 Gb/s',
            readSpeed: '3500 MB per second',
            writeSpeed: '550 MBps',
            cacheSize: '16',
            warranty: '24 months',
            compatibleDevices: 'Desktop',
            SATAcableIncluded: 'Yes'
        },
        {
            name: 'Sabrent 2TB SSD',
            brand: 'Sabrent',
            productDimensions: '7.9 x 2.5 x 2.3 cm; 30 Grams',
            itemModelNumber: 'ASX8200PNP-512GT-C',
            manufacturer: 'ADATA',
            series: 'XPG SX8200 Pro',
            color: 'Silver',
            formFactor: '',
            hardDriveSize: '2 TB',
            hardDiskDescription: 'Solid State Hard Drive',
            wattage: '23',
            powerSource: 'System Powered',
            revolutionsPerMinute: '2280',
            hardwareInterface: 'SATA 6.0 Gb/s',
            readSpeed: '3500 MB per second',
            writeSpeed: '550 MBps',
            cacheSize: '16',
            warranty: '24 months',
            compatibleDevices: 'Desktop',
            SATAcableIncluded: 'Yes'
        },
        {
            name: 'Cruical 1TB SSD',
            brand: 'Cruical',
            productDimensions: '7.9 x 2.5 x 2.3 cm; 30 Grams',
            itemModelNumber: 'ASX8200PNP-512GT-C',
            manufacturer: 'ADATA',
            series: 'XPG SX8200 Pro',
            color: 'Silver',
            formFactor: '',
            hardDriveSize: '2 TB',
            hardDiskDescription: 'Solid State Hard Drive',
            wattage: '23',
            powerSource: 'System Powered',
            revolutionsPerMinute: '2280',
            hardwareInterface: 'SATA 6.0 Gb/s',
            readSpeed: '3500 MB per second',
            writeSpeed: '550 MBps',
            cacheSize: '16',
            warranty: '24 months',
            compatibleDevices: 'Desktop',
            SATAcableIncluded: 'Yes'
        },
        {
            name: 'WD BLUE 500GB SSD',
            brand: 'WD Blue',
            productDimensions: '7.9 x 2.5 x 2.3 cm; 30 Grams',
            itemModelNumber: 'ASX8200PNP-512GT-C',
            manufacturer: 'ADATA',
            series: 'XPG SX8200 Pro',
            color: 'Silver',
            formFactor: '',
            hardDriveSize: '2 TB',
            hardDiskDescription: 'Solid State Hard Drive',
            wattage: '23',
            powerSource: 'System Powered',
            revolutionsPerMinute: '2280',
            hardwareInterface: 'SATA 6.0 Gb/s',
            readSpeed: '3500 MB per second',
            writeSpeed: '550 MBps',
            cacheSize: '16',
            warranty: '24 months',
            compatibleDevices: 'Desktop',
            SATAcableIncluded: 'Yes'
        },
        {
            name: 'Kingston 240GB SSD',
            brand: 'Kingston',
            productDimensions: '7.9 x 2.5 x 2.3 cm; 30 Grams',
            itemModelNumber: 'ASX8200PNP-512GT-C',
            manufacturer: 'ADATA',
            series: 'XPG SX8200 Pro',
            color: 'Silver',
            formFactor: '',
            hardDriveSize: '2 TB',
            hardDiskDescription: 'Solid State Hard Drive',
            wattage: '23',
            powerSource: 'System Powered',
            revolutionsPerMinute: '2280',
            hardwareInterface: 'SATA 6.0 Gb/s',
            readSpeed: '3500 MB per second',
            writeSpeed: '550 MBps',
            cacheSize: '16',
            warranty: '24 months',
            compatibleDevices: 'Desktop',
            SATAcableIncluded: 'Yes'
        }
]

module.exports = { productDetails }
